[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  external_node_modules = ["@sparticuz/chromium-min"]
  included_files = ["node_modules/@sparticuz/chromium-min/**/*"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20.9.0"
  PNPM_FLAGS = "--shamefully-hoist"