[build]
  functions = "netlify/functions"
  command = "pnpm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[dev]
  port = 8888
  targetPort = 3000
  framework = "#static"  # Change to static since we're not running a framework