[build]
  functions = "netlify/functions"
  command = "pnpm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  PNPM_FLAGS = "--version"