[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["@sparticuz/chromium"]
  included_files = ["node_modules/@sparticuz/chromium/**/*"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"