[build]
  functions = "netlify/functions"
  command = "pnpm run build"

[functions]
  external_node_modules = ["@sparticuz/chromium"]
  included_files = ["node_modules/@sparticuz/chromium/**/*"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20.9.0"
  PNPM_FLAGS = "--shamefully-hoist"