[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[dev]
  port = 8888
  publish = "public"
  functions = "netlify/functions"
  targetPort = 3000